sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
script:
  - make test
after_success:
  - make babel-build
  - if [[ $TRAVIS_NODE_VERSION == "7" ]]; then make codecov; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
